### ISSUE TITLE
Ability to add additional disks

### ISSUE THREAD

**Issue by Belogix** [chef/kitchen-vcenter#71]
### Describe the Enhancement:
We create machines that need more than one disk mounted. It would be useful to be able to add additional disks at machine creation.

### Describe the Need:
This would benefit anyone who needs more than just one disk. This is useful to check Chef recipes that mount disks etc to ensure it all works as expected.

### Current Alternative
None - Have to manually add disk or ensure templates have additional disks at this time.

### Can We Help You Implement This?:
We are evaluating this provisioner as we currently use the now deprecated Provisioning vSphere driver (https://github.com/chef-boneyard/chef-provisioning-vsphere) which has this functionality.

**Comment by tecracer-theinen** [comment]
This is a great idea, but please keep in mind that this is a driver for creating TestKitchen machines and not a provisioner for virtual infrastructure. If you need provisioning, that will most likely need a lot of features for various specialized functionality which is not a primary thing for test instances in development or CI/CD pipelines.

Some provisioning functionality is included in the knife-vcenter project though. I have just updated that one for the new vSphere APIs though and there is no easy cross-project portability of features yet. If you are evaluating that tool, I can do my best for adding features but kitchen-vcenter is more of a priority on my side (mostly due to customer demand).

As this feature makes sense for e.g. testing Chef Cookbooks and their reaction to different disk configurations, I see it as a viable one and will add it to my backlog.

**Comment by tas50** [comment]
Closing this with the merging of #76
